kind: pipeline
name: compatibility
steps:
  - name: compatibility
    image: nextcloudci/php7.4:latest
    environment:
      APP_NAME: officeonline
      CORE_BRANCH: stable22
      DB: sqlite
    commands:
      - composer install
      - bash ./tests/drone-server-setup.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - ./occ app:check-code $APP_NAME -c strong-comparison
      # TODO: disabled until we have a proper api in the server for static calls
      - ./occ app:check-code $APP_NAME -c deprecation || true
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
name: syntax
steps:
  - name: syntax-php7.4
    image: nextcloudci/php7.4:latest
    commands:
      - composer install
      - find lib/ -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
  - name: syntax-php7.3
    image: nextcloudci/php7.3:php7.3-2
    commands:
      - composer install
      - find lib/ -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
name: integration

steps:
    - name: nextcloud
      image: nextcloudci/php7.4:latest
      environment:
          APP_NAME: officeonline
          CORE_BRANCH: master
          DB: sqlite
      commands:
          - bash ./tests/drone-server-setup.sh $APP_NAME $CORE_BRANCH $DB
          - cd ../server
          - ./occ app:enable $APP_NAME
          - ./occ config:system:set allow_local_remote_servers --value true --type bool
          - cd apps/$APP_NAME

          # Run integration tests
          - cd tests
          - bash run-integration.sh features/wopi
services:
    - name: collabora
      image: collabora/code:latest
      environment:
          extra_params: '--o:ssl.enable=false'
          domain: 'nextcloud'

trigger:
    branch:
        - master
        - stable*
    event:
        - pull_request
        - push
